#!/usr/bin/env bash

SCRIPT_DIR=$(dirname "${BASH_SOURCE[0]}") 

cd $SCRIPT_DIR/../packages

cd utils 
pnpm prettier --write .
cd ..

cd webapp
pnpm prettier --write .
cd ..

cd webapi
pnpm prettier --write .
cd ..